
version: build{build}
branches:
  only:
    - master
    - develop
environment:
  CODECAKEBUILDER_SECRET_KEY:
    secure: 8VAzdXgUQaJyFoU3WLf2iPFV/8zPDm9qV4TfOpx8/rg=
install:
  - ps: ./CodeCakeBuilder/InstallCredentialProvider.ps1
build_script:
  - dotnet run --project CodeCakeBuilder -nointeraction
test: off
image: Visual Studio 2017
clone_folder: C:\CKli-World\CK-Core-Projects\CK-Globbing
